ADD Future Enhancements / Roadmap on the README file
yashksaini-coder/BookStream pull request #60
Opened 2024-10-15 18:36 UTC by alo7lika

**Closes : #59 **
Here's a point-wise summary of the updates made to the README:

- Added Hacktoberfest Banner: A banner was added to promote participation in Hacktoberfest.

- Added GSSoC Banner: A banner was added to highlight participation in the GirlScript Summer of Code.

- Enhanced the README: Improved the overall readability and structure of the README for a better user experience.

- Added Future Enhancements / Roadmap: Introduced a new section outlining upcoming features and improvements planned for Bookstream, including:

1. Wishlist Integration
2. Ratings & Reviews
3. Admin Dashboard
4. Book Recommendations
5. Multilingual Support

Structured the README: I organized the content into clear sections with headings, bullet points, and tables of contents for easier navigation.

This summary captures the significant enhancements made to the README file effectively.

2024-10-15 18:38 UTC, alo7lika commented
@yashksaini-coder I have completed the task. Please review it.
Thank you!

2024-10-15 18:39 UTC, yashksaini-coder commented
> @yashksaini-coder I have completed the task. Please review it. Thank you!

Have you read the #24 discussion if not please go through it first. @alo7lika

2024-10-15 18:43 UTC, yashksaini-coder requested changes
- Remove the GSSOC banner
- Add more improve image badges & social badges

2024-10-15 18:43 UTC, yashksaini-coder commented on README/329829127-e79eb6de-81b1-4ffb-b6ed-f018bb977e88.png
Remove this as this project is not a part of GSSOC-Ext anymore.

2024-10-15 18:43 UTC, yashksaini-coder commented on README.md
Can you add more extra badges and social icons like this but more better than these, don't just copy paste this.

![image](https://github.com/user-attachments/assets/ad36e984-5189-4055-aa22-4ab1b8165b70)

2024-10-15 18:43 UTC, alo7lika commented
> > @yashksaini-coder I have completed the task. Please review it. Thank you!
> 
> Have you read the #24 discussion if not please go through it first. @alo7lika

yes read it

2024-10-15 18:47 UTC, yashksaini-coder commented
> > > @yashksaini-coder I have completed the task. Please review it. Thank you!
> > 
> > 
> > Have you read the #24 discussion if not please go through it first. @alo7lika
> 
> yes read it

okh I hope you understand.

2024-10-16 17:38 UTC, yashksaini-coder approved these changes
Its good

2024-10-16 17:40 UTC, merged